### ISSUE TITLE
SSHing into Karaf shell fails on F23

### ISSUE THREAD

**Issue by dfarrell07** [dfarrell07/vagrant-opendaylight#29]
On Fedora 23, connecting to the Karaf shell via SSH fails with

```
[vagrant@localhost ~]$ ssh -p 8101 karaf@localhost
Unable to negotiate with ::1: no matching host key type found. Their offer: ssh-dss
```

```
[vagrant@localhost ~]$ /vagrant/scripts/connect.sh 
Will repeatedly attempt connecting to Karaf shell until it's ready
Unable to negotiate with ::1: no matching host key type found. Their offer: ssh-dss
```

I can start an interactive Karaf shell and work with it normally, but this isn't helpful when ODL is managed by systemd.

```
[vagrant@localhost ~]$ sudo systemctl stop opendaylight
[vagrant@localhost ~]$ cd /opt/opendaylight/bin/
[vagrant@localhost bin]$ pgrep java
[vagrant@localhost bin]$ sudo ./karaf
# works
```

**Comment by rski** [comment]
This looks like it's an issue with openssh, because it [deprecates the ssh-dss algorithm](http://www.openssh.com/legacy.html)
If you enable it, connect.sh works again:

``` shell
[vagrant@10 ~]$ cat .ssh/config 
Host localhost
    HostkeyAlgorithms ssh-dss
[vagrant@10 ~]$ /vagrant/scripts/connect.sh 
Will repeatedly attempt connecting to Karaf shell until it's ready
Warning: Permanently added '[localhost]:8101' (DSA) to the list of known hosts.

    ________                       ________                .__  .__       .__     __       
    \_____  \ ______   ____   ____ \______ \ _____  ___.__.|  | |__| ____ |  |___/  |_     
     /   |   \\____ \_/ __ \ /    \ |    |  \\__  \<   |  ||  | |  |/ ___\|  |  \   __\    
    /    |    \  |_> >  ___/|   |  \|    `   \/ __ \\___  ||  |_|  / /_/  >   Y  \  |      
    \_______  /   __/ \___  >___|  /_______  (____  / ____||____/__\___  /|___|  /__|      
            \/|__|        \/     \/        \/     \/\/            /_____/      \/          


Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown OpenDaylight.

opendaylight-user@root>
```

CentOS works because it still ships OpenSSH 6.6.1. I actually have no idea how to go about solving without adding the above .ssh/config to the vm, because I don't know how odl/karaf handles its keys

**Comment by dfarrell07** [comment]
Just talked to a teammate about this
- Should be fixed with latest JDK in Fedora
- He's working on ODL NetConf guys for a fix in ODL right now
- If neither of those fix it, will be fixed by Karaf upgrade (3.0.3?) going into ODL in next few days

**Comment by skitt** [comment]
Actually I misread the bug report; the fixes we're working on in ODL are unlikely to fix the SSH issue. The recommended method to connect to Karaf via SSH is to use the client script; that should work fine currently.

(Using SSH in its default configuration will probably only be fixed with an upgrade to Karaf 4, which isn't planned for Boron.)

**Comment by vorburger** [comment]
@dfarrell07 FYI our upstream issue is https://jira.opendaylight.org/projects/ODLPARENT/issues/ODLPARENT-113
